[[redirects]]
    from = "/api/*"    
    to = "/.netlify/:splat"    
    status = 200
    force = true

[[redirects]]
    from = "/*"    
    to = "index.html"    
    status = 200

[images]
  remote_images = ["https://assets.myntassets.com/.*"]