[context.production.environment]
    VITE_SERVER = "https://server.retail-demo.aerospike.com"

[[redirects]]
    from = "/*"    
    to = "index.html"    
    status = 200

[images]
  remote_images = ["https:\\/\\/assets\\.myntassets\\.com\\/.*"]